@ cdecl winedmo_demuxer_check(str)
@ cdecl winedmo_demuxer_create(wstr ptr int64 ptr ptr ptr ptr)
@ cdecl winedmo_demuxer_destroy(ptr)
@ cdecl winedmo_demuxer_read(int64 ptr ptr ptr)
@ cdecl winedmo_demuxer_seek(int64 int64)
@ cdecl winedmo_demuxer_stream_lang(int64 long ptr long)
@ cdecl winedmo_demuxer_stream_name(int64 long ptr long)
@ cdecl winedmo_demuxer_stream_type(int64 long ptr ptr)

@ cdecl winedmo_muxer_check(ptr)
@ cdecl winedmo_muxer_create(ptr ptr)
@ cdecl winedmo_muxer_destroy(int64)
@ cdecl winedmo_muxer_add_stream(int64)
@ cdecl winedmo_muxer_start(int64)
@ cdecl winedmo_muxer_write(int64 ptr)

@ cdecl winedmo_transform_check(int128 ptr ptr)
@ cdecl winedmo_transform_create(ptr ptr ptr)
@ cdecl winedmo_transform_destroy(int64)
@ cdecl winedmo_transform_get_output_type(int64 ptr)
@ cdecl winedmo_transform_set_output_type(int64 ptr)
@ cdecl winedmo_transform_process_input(int64 ptr)
@ cdecl winedmo_transform_process_output(int64 ptr ptr)
@ cdecl winedmo_transform_drain(int64)
