#!/bin/bash

echo "Building $(git log -1)"
echo "---"

set -Eeux

./tools/make_requests
./tools/make_makefiles
autoreconf

cd build64
../configure -q -C --enable-win64 --enable-werror --with-mingw
make -s -j$(nproc) GIT=true
cd ..

cd build32
../configure -q -C --enable-werror --with-mingw
make -s -j$(nproc) GIT=true
cd ..

TESTS="$(git diff --name-only $CI_MERGE_REQUEST_DIFF_BASE_SHA dlls/ programs/ | \
         sed -re 's:^([^/]+/[^/]+).*$:\1/tests:' | sort -u | \
         xargs -r ls -d 2>/dev/null | sed -re 's:/tests$:/tests/check:')"

if ! test -z "$TESTS"
then
    WINEPREFIX=$PWD/.wine64 WINEARCH=win64 make -C build64 -s $TESTS
    WINEPREFIX=$PWD/.wine32 WINEARCH=win32 make -C build32 -s $TESTS
fi

if ! test -s .git/rebase-merge/git-rebase-todo
then
    make -s -j$(nproc) -C build32 all install-lib install-test DESTDIR=$BASEDIR
    make -s -j$(nproc) -C build64 all install-lib install-test DESTDIR=$BASEDIR
fi

git reset --hard
