#!/bin/bash

python bin/git_sha1_gen.py --output src/git_sha1.h
python src/compiler/builtin_types_c.py src/compiler/builtin_types.c
python src/compiler/builtin_types_h.py src/compiler/builtin_types.h
python src/compiler/glsl/ir_expression_operation.py constant >src/compiler/glsl/ir_expression_operation_constant.h
python src/compiler/glsl/ir_expression_operation.py enum >src/compiler/ir_expression_operation.h
python src/compiler/glsl/ir_expression_operation.py strings >src/compiler/glsl/ir_expression_operation_strings.h
python src/compiler/nir/nir_builder_opcodes_h.py >src/compiler/nir/nir_builder_opcodes.h
python src/compiler/nir/nir_constant_expressions.py >src/compiler/nir/nir_constant_expressions.c
python src/compiler/nir/nir_intrinsics_c.py --outdir src/compiler/nir
python src/compiler/nir/nir_intrinsics_h.py --outdir src/compiler/nir
python src/compiler/nir/nir_intrinsics_indices_h.py --outdir src/compiler/nir
python src/compiler/nir/nir_opcodes_c.py >src/compiler/nir/nir_opcodes.c
python src/compiler/nir/nir_opcodes_h.py >src/compiler/nir/nir_opcodes.h
python src/compiler/nir/nir_opt_algebraic.py --out src/compiler/nir/nir_opt_algebraic.c
python src/compiler/spirv/spirv_info_gen.py --json src/compiler/spirv/spirv.core.grammar.json --out-h src/compiler/spirv/spirv_info.h --out-c src/compiler/spirv/spirv_info.c
python src/compiler/spirv/vtn_gather_types_c.py src/compiler/spirv/spirv.core.grammar.json src/compiler/spirv/vtn_gather_types.c
python src/compiler/spirv/vtn_generator_ids_h.py src/compiler/spirv/spir-v.xml src/compiler/spirv/vtn_generator_ids.h
python src/gallium/auxiliary/driver_trace/enums2names.py src/gallium/include/pipe/p_defines.h src/gallium/include/pipe/p_video_enums.h src/util/blend.h -C src/gallium/auxiliary/tr_util.c -H src/gallium/auxiliary/tr_util.h -I tr_util.h
python src/gallium/auxiliary/indices/u_indices_gen.py src/gallium/auxiliary/u_indices_gen.c
python src/gallium/drivers/zink/nir_to_spirv/zink_nir_algebraic.py -p src/compiler/nir/ >src/gallium/drivers/zink/zink_nir_algebraic.c
python src/gallium/drivers/zink/zink_device_info.py src/gallium/drivers/zink/zink_device_info.h src/gallium/drivers/zink/zink_device_info.c src/vulkan/registry/vk.xml
python src/gallium/drivers/zink/zink_instance.py src/gallium/drivers/zink/zink_instance.h src/gallium/drivers/zink/zink_instance.c src/vulkan/registry/vk.xml
python src/mapi/glapi/gen/api_beginend_init_h.py -f src/mapi/glapi/gen/gl_and_es_API.xml >src/mapi/glapi/gen/api_beginend_init.h
python src/mapi/glapi/gen/api_exec_decl_h.py -f src/mapi/glapi/gen/gl_and_es_API.xml >src/mapi/glapi/gen/api_exec_decl.h
python src/mapi/glapi/gen/api_exec_init.py -f src/mapi/glapi/gen/gl_and_es_API.xml >src/mapi/glapi/gen/api_exec_init.c
python src/mapi/glapi/gen/api_hw_select_init_h.py -f src/mapi/glapi/gen/gl_API.xml >src/mapi/glapi/gen/api_hw_select_init.h
python src/mapi/glapi/gen/api_save_h.py -f src/mapi/glapi/gen/gl_and_es_API.xml >src/mapi/glapi/gen/api_save.h
python src/mapi/glapi/gen/api_save_init_h.py -f src/mapi/glapi/gen/gl_and_es_API.xml >src/mapi/glapi/gen/api_save_init.h
python src/mapi/glapi/gen/gl_apitemp.py -f src/mapi/glapi/gen/gl_and_es_API.xml >src/mapi/glapi/gen/glapitemp.h
python src/mapi/glapi/gen/gl_enums.py -f src/mapi/glapi/registry/gl.xml >src/mapi/glapi/gen/enums.c
python src/mapi/glapi/gen/gl_marshal.py src/mapi/glapi/gen/gl_and_es_API.xml 0 8 8 >src/mapi/glapi/gen/marshal_generated0.c
python src/mapi/glapi/gen/gl_marshal.py src/mapi/glapi/gen/gl_and_es_API.xml 1 8 8 >src/mapi/glapi/gen/marshal_generated1.c
python src/mapi/glapi/gen/gl_marshal.py src/mapi/glapi/gen/gl_and_es_API.xml 2 8 8 >src/mapi/glapi/gen/marshal_generated2.c
python src/mapi/glapi/gen/gl_marshal.py src/mapi/glapi/gen/gl_and_es_API.xml 3 8 8 >src/mapi/glapi/gen/marshal_generated3.c
python src/mapi/glapi/gen/gl_marshal.py src/mapi/glapi/gen/gl_and_es_API.xml 4 8 8 >src/mapi/glapi/gen/marshal_generated4.c
python src/mapi/glapi/gen/gl_marshal.py src/mapi/glapi/gen/gl_and_es_API.xml 5 8 8 >src/mapi/glapi/gen/marshal_generated5.c
python src/mapi/glapi/gen/gl_marshal.py src/mapi/glapi/gen/gl_and_es_API.xml 6 8 8 >src/mapi/glapi/gen/marshal_generated6.c
python src/mapi/glapi/gen/gl_marshal.py src/mapi/glapi/gen/gl_and_es_API.xml 7 8 8 >src/mapi/glapi/gen/marshal_generated7.c
python src/mapi/glapi/gen/gl_marshal_h.py src/mapi/glapi/gen/gl_and_es_API.xml 8 >src/mesa/main/marshal_generated.h
python src/mapi/glapi/gen/gl_procs.py -c -f src/mapi/glapi/gen/gl_and_es_API.xml >src/mapi/glapi/gen/glprocs.h
python src/mapi/glapi/gen/gl_table.py -f src/mapi/glapi/gen/gl_and_es_API.xml -m remap_table >src/mesa/main/dispatch.h
python src/mapi/glapi/gen/gl_table.py -f src/mapi/glapi/gen/gl_and_es_API.xml >src/mapi/glapi/gen/glapitable.h
python src/mapi/glapi/gen/gl_unmarshal_table.py src/mapi/glapi/gen/gl_and_es_API.xml 8 >src/mapi/glapi/gen/unmarshal_table.c
python src/mapi/glapi/gen/remap_helper.py -f src/mapi/glapi/gen/gl_and_es_API.xml >src/mesa/main/remap_helper.h
python src/mesa/main/format_fallback.py src/mesa/main/formats.csv src/mesa/format_fallback.c
python src/mesa/main/format_info.py src/mesa/main/formats.csv >src/mesa/format_info.h
python src/mesa/main/get_hash_generator.py -f src/mapi/glapi/gen/gl_and_es_API.xml >src/mesa/get_hash.h
python src/util/driconf_static.py src/util/00-mesa-defaults.conf src/util/driconf_static.h
python src/util/format/u_format_table.py src/util/format/u_format.yaml --header >src/util/format/u_format_pack.h
python src/util/format/u_format_table.py src/util/format/u_format.yaml >src/util/format/u_format_table.c
python src/util/format/u_format_table.py src/util/format/u_format.yaml --enums >src/util/format/u_format_gen.h
python src/util/format_srgb.py >src/util/format_srgb.c
python src/util/xxd.py src/compiler/glsl/astc_decoder.glsl src/compiler/glsl/astc_glsl.h -n astc_source
python src/util/xxd.py src/compiler/glsl/bc1.glsl src/compiler/glsl/bc1_glsl.h -n bc1_source
python src/util/xxd.py src/compiler/glsl/bc4.glsl src/compiler/glsl/bc4_glsl.h -n bc4_source
python src/util/xxd.py src/compiler/glsl/CrossPlatformSettings_piece_all.glsl src/compiler/glsl/cross_platform_settings_piece_all.h -n cross_platform_settings_piece_all_header
python src/util/xxd.py src/compiler/glsl/etc2_rgba_stitch.glsl src/compiler/glsl/etc2_rgba_stitch_glsl.h -n etc2_rgba_stitch_source
python src/util/xxd.py src/compiler/glsl/float64.glsl src/compiler/glsl/float64_glsl.h -n float64_source
python src/vulkan/util/gen_enum_to_str.py --xml src/vulkan/registry/vk.xml --outdir src/vulkan/util --beta false
python src/vulkan/util/vk_dispatch_table_gen.py --xml src/vulkan/registry/vk.xml --out-c src/vulkan/util/vk_dispatch_table.c --out-h src/vulkan/util/vk_dispatch_table.h --beta false
python src/vulkan/util/vk_extensions_gen.py --xml src/vulkan/registry/vk.xml --out-c src/vulkan/util/vk_extensions.c --out-h src/vulkan/util/vk_extensions.h
python src/vulkan/util/vk_struct_type_cast_gen.py --xml src/vulkan/registry/vk.xml --outdir src/vulkan/util --beta false
